export const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export const cityToIata: Record<string, string> = {
  'Aguadilla': 'BQN',
  'Atlanta, GA': 'ATL',
  'Austin, TX': 'AUS',
  'Baltimore, MD': 'BWI',
  'Bentonville/Fayetteville, AR': 'XNA',
  'Boise, ID': 'BOI',
  'Boston, MA': 'BOS',
  'Buffalo, NY': 'BUF',
  'Burbank': 'BUR',
  'Cabo San Lucas': 'SJD',
  'Cancun, MX': 'CUN',
  'Cedar Rapids, IA': 'CID',
  'Charleston, SC': 'CHS',
  'Charlotte, NC': 'CLT',
  'Chicago, IL': 'ORD',
  'Cincinnati, OH': 'CVG',
  'Cleveland, OH': 'CLE',
  'Columbus, OH': 'CMH',
  'Corpus Christi': 'CRP',
  'Dallas, TX': 'DFW',
  'Denver, CO': 'DEN',
  'Des Moines, IA': 'DSM',
  'Detroit, MI': 'DTW',
  'El Paso, TX': 'ELP',
  'Fargo, ND': 'FAR',
  'Fort Lauderdale, FL': 'FLL',
  'Fort Myers, FL': 'RSW',
  'Grand Rapids, MI': 'GRR',
  'Guatemala City': 'GUA',
  'Harrisburg, PA': 'MDT',
  'Hartford, CT': 'BDL',
  'Houston, TX': 'IAH',
  'Indianapolis, IN': 'IND',
  'Islip, NY': 'ISP',
  'Jacksonville, FL': 'JAX',
  'Kansas City, MO': 'MCI',
  'Knoxville, TN': 'TYS',
  'Las Vegas, NV': 'LAS',
  'Little Rock, AR': 'LIT',
  'Los Angeles, CA': 'LAX',
  'Madison, WI': 'MSN',
  'Memphis, TN': 'MEM',
  'Miami, FL': 'MIA',
  'Milwaukee, WI': 'MKE',
  'Minneapolis/St. Paul, MN': 'MSP',
  'Montego Bay, Jamaica': 'MBJ',
  'Myrtle Beach, SC': 'MYR',
  'Nashville, TN': 'BNA',
  'Nassau': 'NAS',
  'New Orleans, LA': 'MSY',
  'New York City, NY': 'LGA',
  'Newark, NJ': 'EWR',
  'Norfolk, VA': 'ORF',
  'Oklahoma City, OK': 'OKC',
  'Omaha, NE': 'OMA',
  'Ontario/LA, CA': 'ONT',
  'Oranjestad, Aruba': 'AUA',
  'Orlando, FL': 'MCO',
  'Pensacola, FL': 'PNS',
  'Philadelphia, PA': 'PHL',
  'Phoenix, AZ': 'PHX',
  'Pittsburgh, PA': 'PIT',
  'Ponce': 'PSE',
  'Portland, OR': 'PDX',
  'Providenciales': 'PLS',
  'Puerto Vallarta, Mexico': 'PVR',
  'Punta Cana, Dominican Republic': 'PUJ',
  'Raleigh, NC': 'RDU',
  'Reno, NV': 'RNO',
  'Richmond': 'RIC',
  'Sacramento, CA': 'SMF',
  'Salt Lake City, UT': 'SLC',
  'San Antonio, TX': 'SAT',
  'San Diego, CA': 'SAN',
  'San Francisco, CA': 'SFO',
  'San Jose, CA': 'SJC',
  'San Jose, CR': 'SJO',
  'San Juan, PR': 'SJU',
  'San Pedro Sula': 'SAP',
  'San Salvador': 'SAL',
  'Santa Ana, CA': 'SNA',
  'Santiago de los Caballeros': 'STI',
  'Santo Domingo': 'SDQ',
  'Sarasota, FL': 'SRQ',
  'Seattle, WA': 'SEA',
  'Sioux Falls, SD': 'FSD',
  'Spokane, WA': 'GEG',
  'St. Louis, MO': 'STL',
  'St. Maarten': 'SXM',
  'Syracuse, NY': 'SYR',
  'Tampa, FL': 'TPA',
  'Trenton, NJ': 'TTN',
  'Tucson, AZ': 'TUS',
  'Tulsa, OK': 'TUL',
  'Washington, D.C.': 'IAD',
  'West Palm Beach, FL': 'PBI',
};

export function buildFrontierUrl(from: string, to: string, date: string): string {
  const o1 = cityToIata[from];
  const d1 = cityToIata[to];
  if (!o1 || !d1 || !date) return '';
  const [year, month, day] = date.split('-');
  const monthName = MONTHS[parseInt(month) - 1];
  const dd1 = encodeURIComponent(`${monthName} ${parseInt(day)}, ${year}`);
  return `https://booking.flyfrontier.com/Flight/InternalSelect?o1=${o1}&d1=${d1}&dd1=${dd1}&ADT=1&mon=true&promo=&ftype=DD`;
}
