export const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export const cityToIata: Record<string, string> = {
  'Aguascalientes, Mexico': 'AGU',
  'Atlanta, GA': 'ATL',
  'Aruba, Aruba': 'AUA',
  'Austin, TX': 'AUS',
  'Hartford, CT': 'BDL',
  'Leon, Mexico': 'BJX',
  'Nashville, TN': 'BNA',
  'Boise, ID': 'BOI',
  'Boston, MA': 'BOS',
  'Aguadilla, PR': 'BQN',
  'Buffalo, NY': 'BUF',
  'Hollywood Burbank/LA, CA': 'BUR',
  'Baltimore, MD': 'BWI',
  'Charleston, SC': 'CHS',
  'Cedar Rapids, IA': 'CID',
  'Ciudad Juarez, Mexico': 'CJS',
  'Cleveland, OH': 'CLE',
  'Charlotte, NC': 'CLT',
  'Columbus, OH': 'CMH',
  'Corpus Christi, TX': 'CRP',
  'Culiacan, Mexico': 'CUL',
  'Cancun, Mexico': 'CUN',
  'Chihuahua, Mexico': 'CUU',
  'Cincinnati, OH': 'CVG',
  'Washington-Reagan, DC': 'DCA',
  'Denver, CO': 'DEN',
  'Dallas/Ft. Worth, TX': 'DFW',
  'Durango, Mexico': 'DGO',
  'Des Moines, IA': 'DSM',
  'Detroit, MI': 'DTW',
  'El Paso, TX': 'ELP',
  'Newark, NJ': 'EWR',
  'Fargo, ND': 'FAR',
  'Fort Lauderdale, FL': 'FLL',
  'Sioux Falls, SD': 'FSD',
  'Guadalajara, Mexico': 'GDL',
  'Spokane, WA': 'GEG',
  'Grand Rapids, MI': 'GRR',
  'Guatemala City, Guatemala': 'GUA',
  'Hermosillo, Mexico': 'HMO',
  'Huatulco, Mexico': 'HUX',
  'Washington-Dulles, VA': 'IAD',
  'Houston-Intercontinental, TX': 'IAH',
  'Indianapolis, IN': 'IND',
  'Long Island/Islip, NY': 'ISP',
  'Jacksonville, FL': 'JAX',
  'New York (JFK), NY': 'JFK',
  'Las Vegas, NV': 'LAS',
  'Los Angeles, CA': 'LAX',
  'New York-LaGuardia, NY': 'LGA',
  'Little Rock, AR': 'LIT',
  'Montego Bay, Jamaica': 'MBJ',
  'Kansas City, MO': 'MCI',
  'Orlando, FL': 'MCO',
  'Harrisburg, PA': 'MDT',
  'Chicago-Midway, IL': 'MDW',
  'Memphis, TN': 'MEM',
  'Mexico City, Mexico': 'MEX',
  'Miami, FL': 'MIA',
  'Milwaukee, WI': 'MKE',
  'Morelia, Mexico': 'MLM',
  'Madison, WI': 'MSN',
  'Minneapolis/St. Paul, MN': 'MSP',
  'New Orleans, LA': 'MSY',
  'Monterrey, Mexico': 'MTY',
  'Mexicali, Mexico': 'MXL',
  'Myrtle Beach, SC': 'MYR',
  'Nassau, Bahamas': 'NAS',
  'Mexico City (AIFA), Mexico': 'NLU',
  'Oakland, CA': 'OAK',
  'Oaxaca, Mexico': 'OAX',
  'Oklahoma City, OK': 'OKC',
  'Omaha, NE': 'OMA',
  'Ontario/LA, CA': 'ONT',
  'Chicago-O\'Hare, IL': 'ORD',
  'Norfolk, VA': 'ORF',
  'Puebla, Mexico': 'PBC',
  'Palm Beach, FL': 'PBI',
  'Portland, OR': 'PDX',
  'Philadelphia, PA': 'PHL',
  'Phoenix-Sky Harbor, AZ': 'PHX',
  'Pittsburgh, PA': 'PIT',
  'Providenciales, Turks and Caicos': 'PLS',
  'Pensacola, FL': 'PNS',
  'Ponce, PR': 'PSE',
  'Punta Cana, Dominican Republic': 'PUJ',
  'Puerto Vallarta, Mexico': 'PVR',
  'Querétaro, Mexico': 'QRO',
  'Raleigh/Durham, NC': 'RDU',
  'Richmond, VA': 'RIC',
  'Reno/Tahoe, NV': 'RNO',
  'Fort Myers, FL': 'RSW',
  'San Salvador, El Salvador': 'SAL',
  'San Diego, CA': 'SAN',
  'San Pedro Sula, Honduras': 'SAP',
  'San Antonio, TX': 'SAT',
  'Santo Domingo, Dominican Republic': 'SDQ',
  'Seattle/Tacoma, WA': 'SEA',
  'San Francisco, CA': 'SFO',
  'San Jose, CA': 'SJC',
  'Cabo San Lucas, Mexico': 'SJD',
  'San Jose, Costa Rica': 'SJO',
  'San Juan, Puerto Rico': 'SJU',
  'Salt Lake City, UT': 'SLC',
  'San Luis Potosi, Mexico': 'SLP',
  'Sacramento, CA': 'SMF',
  'Orange County/Santa Ana, CA': 'SNA',
  'Sarasota, FL': 'SRQ',
  'Santiago, Dominican Republic': 'STI',
  'St. Louis, MO': 'STL',
  'St. Maarten, St. Maarten': 'SXM',
  'Syracuse, NY': 'SYR',
  'Tuxtla Gutiérrez, Mexico': 'TGZ',
  'Tijuana, Mexico': 'TIJ',
  'Toluca, Mexico': 'TLC',
  'Tampa, FL': 'TPA',
  'Trenton/Princeton, NJ': 'TTN',
  'Tulsa, OK': 'TUL',
  'Tucson, AZ': 'TUS',
  'Knoxville, TN': 'TYS',
  'Uruapan, Mexico': 'UPN',
  'Bentonville/Fayetteville, AR': 'XNA',
  'Zacatecas, Mexico': 'ZCL',
};

export function buildFrontierUrl(from: string, to: string, date: string): string {
  const o1 = cityToIata[from];
  const d1 = cityToIata[to];
  if (!o1 || !d1 || !date) return '';
  const [year, month, day] = date.split('-');
  const monthName = MONTHS[parseInt(month) - 1];
  const dd1 = encodeURIComponent(`${monthName} ${parseInt(day)}, ${year}`);
  return `https://booking.flyfrontier.com/Flight/InternalSelect?o1=${o1}&d1=${d1}&dd1=${dd1}&ADT=1&mon=true&promo=&ftype=DD`;
}
